services:
  - type: web
    name: mytelegrambot
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    pythonVersion: 3.11.9
