services:
  - type: web
    name: mytelegrambot
    env: python
    buildCommand: |
      export AIOHTTP_NO_EXTENSIONS=1
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: AIOHTTP_NO_EXTENSIONS
        value: "1"
